site_name: Yale Center for Research Computing
site_description: Yale Center for Research Computing Documentation
site_author: YCRC
site_url: https://docs.ycrc.yale.edu
repo_name: github/ycrc/docs
repo_url: https://github.com/ycrc/ycrc.github.io/tree/src
edit_uri: docs/
remote_branch: master
strict: true

theme:
    name: material
    custom_dir: 'theme'
    primary: '#0e4c92'
    accent: '#0e4c92'
    logo: 'img/manual.svg'
    favicon: 'assets/images/favicon.ico'

    features:
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections

plugins:
  - search
  - git-revision-date-localized

extra:
  social:
    - icon: material/home-circle
      link: https://ycrc.yale.edu
    - icon: material/help-circle
      link: http://help.ycrc.yale.edu/
    - icon: material/heart-pulse
      link: https://research.computing.yale.edu/system-status
    - icon: fontawesome/brands/github
      link: https://github.com/ycrc
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yalecrc
  analytics:
    provider: google
    property: G-QM84KPHSPL

extra_css:
    - 'stylesheets/extra.css'

extra_javascript:
    - 'js/extra.js'
    - 'https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'

markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - footnotes
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.snippets:
        check_paths: true
    - pymdownx.superfences
    - pymdownx.tabbed
 #   - pymdownx.tabbed:
 #       alternate_style: true
    - pymdownx.tasklist:
        clickable_checkbox: true

nav:
    - About:
        - Introduction: index.md
        - news.md
        - HPC Clusters:
            - "Overview": clusters-at-yale/clusters/index.md
            - clusters-at-yale/clusters/grace.md
            - clusters-at-yale/clusters/farnam.md
            - clusters-at-yale/clusters/ruddle.md
            - clusters-at-yale/clusters/milgram.md
        - About the YCRC: https://research.computing.yale.edu/about

    - User Guide:
        - clusters-at-yale/index.md
        - clusters-at-yale/access/accounts.md
        - Request an Account: https://research.computing.yale.edu/account-request
        - clusters-at-yale/help-requests.md
        - clusters-at-yale/troubleshoot.md
        - Access the Clusters:
            - clusters-at-yale/access/index.md
            - clusters-at-yale/access/ood.md
            - clusters-at-yale/access/vpn.md
            - clusters-at-yale/access/x11.md
            - clusters-at-yale/access/vnc.md
            - clusters-at-yale/access/mfa.md
            - clusters-at-yale/access/advanced-config.md
        - Applications & Software:
            - clusters-at-yale/applications/index.md
            - clusters-at-yale/applications/compile.md
            - "Software Modules": clusters-at-yale/applications/modules.md
            - "Module Toolchains": clusters-at-yale/applications/toolchains.md
            - "Module Lifecycle": clusters-at-yale/applications/lifecycle.md

        - Job Scheduling:
            - clusters-at-yale/job-scheduling/index.md
            - clusters-at-yale/job-scheduling/resource-requests.md
            - clusters-at-yale/job-scheduling/common-job-failures.md
            - clusters-at-yale/job-scheduling/resource-usage.md
            - clusters-at-yale/job-scheduling/fairshare.md
            - clusters-at-yale/job-scheduling/dsq.md
            - clusters-at-yale/job-scheduling/dependency.md
            - clusters-at-yale/job-scheduling/scrontab.md
            - clusters-at-yale/job-scheduling/scavenge.md
            - clusters-at-yale/job-scheduling/mpi.md
            - clusters-at-yale/job-scheduling/slurm-examples.md
        - Transfer Data:
            - "Transfer to Cluster": clusters-at-yale/data/transfer.md
            - clusters-at-yale/data/globus.md
            - "Stage Data for Compute Jobs": clusters-at-yale/data/staging.md
    - Data & Storage:
            - data/index.md
            - clusters-at-yale/data/index.md
            - data/google-drive.md
            - clusters-at-yale/data/archived-sequencing.md
            - Manage & Share:
                - clusters-at-yale/data/permissions.md
                - data/archive.md
                - data/external.md


    - Software & Tools:
        - "Overview": clusters-at-yale/guides/index.md
        - Python: 
            - clusters-at-yale/guides/conda.md
            - clusters-at-yale/guides/python.md
            - clusters-at-yale/guides/jupyter.md
            - "Python+TensorFlow Example": clusters-at-yale/guides/handson-ml2.md
            - "mpi4py": clusters-at-yale/guides/mpi4py.md
        - Software: 
            - clusters-at-yale/guides/cesm.md
            - clusters-at-yale/guides/comsol.md
            - clusters-at-yale/guides/gaussian.md
            - clusters-at-yale/guides/matlab.md
            - clusters-at-yale/guides/mathematica.md
            - clusters-at-yale/guides/namd.md
            - clusters-at-yale/guides/r.md
            - clusters-at-yale/guides/vasp.md
        - Tools:
            - clusters-at-yale/guides/containers.md
            - clusters-at-yale/guides/clustershell.md
            - clusters-at-yale/guides/mysql.md
            - clusters-at-yale/guides/parallel.md
            - clusters-at-yale/guides/rclone.md
            - clusters-at-yale/guides/tmux.md
            - "XVFB": clusters-at-yale/guides/xvfb.md
        - Guides:
            - "Cryo-EM on Farnam": clusters-at-yale/guides/cryoem.md
            - "GitHub": clusters-at-yale/guides/github.md
            - clusters-at-yale/guides/github_pages.md
            - clusters-at-yale/guides/gpus-cuda.md

    - Training & Other Resources:
            - "Overview": resources/index.md
            - Training:
                - "YCRC Workshops": https://research.computing.yale.edu/training
                - "YCRC YouTube Channel": https://ycrc.yale.edu/youtube
                - online-tutorials.md
            - user-group.md
            - national-hpcs.md
            - "Glossary": glossary.md
