site_name: Yale Center for Research Computing
site_description: Yale Center for Research Computing Documentation
site_author: YCRC
site_url: https://docs.ycrc.yale.edu
repo_name: github/ycrc/docs
repo_url: https://github.com/ycrc/ycrc.github.io/tree/src
edit_uri: docs/
remote_branch: master
strict: true

theme:
    name: material
    custom_dir: 'theme'
    primary: '#0e4c92'
    accent: '#0e4c92'
    logo: 'img/manual.svg'
    favicon: 'assets/images/favicon.ico'

    features:
        #- navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections

plugins:
  - search
  - git-revision-date-localized
  - blogging:
        dirs:
            - news
        template: 'theme/partials/news-overrides.html'
        show_total: false  # Remove 'total pages' label
        size: 5
        time_format: '%B %d, %Y'
        meta_time_format: '%Y-%m-%d'

  - redirects:
        redirect_maps:
            'clusters-at-yale/clusters/index.md': 'clusters/index.md'
            'clusters-at-yale/applications/index.md': 'applications/index.md'
            'clusters-at-yale/applications/compile.md': 'applications/compile.md'
            'clusters-at-yale/applications/lifecycle.md': 'applications/lifecycle.md'
            'clusters-at-yale/applications/modules.md': 'applications/modules.md'
            'clusters-at-yale/applications/toolchains.md': 'applications/toolchains.md'

extra:
  social:
    - icon: material/home-circle
      link: https://ycrc.yale.edu
    - icon: material/help-circle
      link: http://help.ycrc.yale.edu/
    - icon: material/heart-pulse
      link: https://research.computing.yale.edu/system-status
    - icon: fontawesome/brands/github
      link: https://github.com/ycrc
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yalecrc
  analytics:
    provider: google
    property: G-QM84KPHSPL

extra_css:
    - '_static/stylesheets/extra.css'

extra_javascript:
    - '_static/js/extra.js'
    - 'https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'

markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - footnotes
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.snippets:
        check_paths: true
    - pymdownx.superfences
    - pymdownx.tabbed
 #   - pymdownx.tabbed:
 #       alternate_style: true
    - pymdownx.tasklist:
        clickable_checkbox: true

nav:
    - About:
        - Introduction: index.md
        - news.md
        - HPC Clusters:
            - "Overview": clusters/index.md
            - clusters/grace.md
            - clusters/mccleary.md
            - clusters/milgram.md
            - clusters/misha.md
            - clusters/bouchet.md
            - "Maintenance": clusters/maintenance.md
        - user-group.md
        - About the YCRC: https://research.computing.yale.edu/about
        - glossary.md

    - User Guide:
        - clusters-at-yale/index.md
        - clusters-at-yale/access/accounts.md
        - Request an Account: https://research.computing.yale.edu/account-request
        - clusters-at-yale/help-requests.md
        - clusters-at-yale/troubleshoot.md
        - Access the Clusters:
            - clusters-at-yale/access/index.md
            - clusters-at-yale/access/ood.md
            - SSH Connection:
                - "Connect with SSH": clusters-at-yale/access/ssh.md
                - clusters-at-yale/access/x11.md
                - clusters-at-yale/access/advanced-config.md
            - clusters-at-yale/access/vpn.md
            - clusters-at-yale/access/mfa.md
            - clusters-at-yale/access/courses.md
        - Applications & Software:
            - applications/index.md
            - applications/compile.md
            - "Software Modules": applications/modules.md
            - "Module Toolchains": applications/toolchains.md
            - "Module Lifecycle": applications/lifecycle.md

        - Job Scheduling:
            - clusters-at-yale/job-scheduling/index.md
            - clusters-at-yale/job-scheduling/resource-requests.md
            - clusters-at-yale/job-scheduling/getusage.md
            - clusters-at-yale/job-scheduling/common-job-failures.md
            - clusters-at-yale/guides/cmd-line-args.md
            - clusters-at-yale/job-scheduling/jobstats.md
            - clusters-at-yale/job-scheduling/fairshare.md
            - clusters-at-yale/job-scheduling/dsq.md
            - clusters-at-yale/job-scheduling/dependency.md
            - clusters-at-yale/job-scheduling/scrontab.md
            - clusters-at-yale/job-scheduling/priority-tier.md
            - clusters-at-yale/job-scheduling/scavenge.md
            - clusters-at-yale/job-scheduling/mpi.md
            - clusters-at-yale/job-scheduling/slurm-examples.md
        - clusters-at-yale/glossary.md
    - Data & Storage:
            - data/index.md
            - data/hpc-storage.md
            - data/backups.md
            - data/google-drive.md
            - data/ycga-data.md
            - Transfer Data:
                - "Transfer to Cluster": data/transfer.md
                - clusters-at-yale/guides/rclone.md
                - data/globus.md
                - "Stage Data for Compute Jobs": data/staging.md
            - Manage & Share:
                - data/permissions.md
                - data/archive.md
                - data/external.md
                - data/group-change.md
            - data/glossary.md


    - Software & Tools:
        - "Overview": clusters-at-yale/guides/index.md
        - Software:
            - Python:
                - clusters-at-yale/guides/python.md
                - clusters-at-yale/guides/conda.md
                - clusters-at-yale/guides/jupyter.md
                - clusters-at-yale/guides/pytorch.md
                - clusters-at-yale/guides/tensorflow.md
                - "MPI with Python": clusters-at-yale/guides/mpi4py.md
            - clusters-at-yale/guides/atlas.md
            - clusters-at-yale/guides/cesm.md
            - clusters-at-yale/guides/comsol.md
            - clusters-at-yale/guides/gaussian.md
            - clusters-at-yale/guides/isca.md
            - clusters-at-yale/guides/matlab.md
            - clusters-at-yale/guides/mathematica.md
            - clusters-at-yale/guides/namd.md
            - clusters-at-yale/guides/nextflow.md
            - clusters-at-yale/guides/r.md
            - clusters-at-yale/guides/vasp.md
        - Tools:
            - clusters-at-yale/guides/containers.md
            - clusters-at-yale/guides/mysql.md
            - clusters-at-yale/guides/parallel.md
            - clusters-at-yale/guides/tmux.md
            - clusters-at-yale/guides/virtualgl.md
            - "XVFB": clusters-at-yale/guides/xvfb.md
        - Guides:
            - "Cryo-EM on McCleary": clusters-at-yale/guides/cryoem.md
            - "GitHub": clusters-at-yale/guides/github.md
            - clusters-at-yale/guides/github_pages.md
            - clusters-at-yale/guides/gpus-cuda.md
            - clusters-at-yale/guides/spark.md

    - Training & Other Resources:
            - "Overview": resources/index.md
            - Tutorials:
                - resources/intro_to_hpc_tutorial.md
                - resources/online-tutorials.md
                - resources/yale_library.md
                - resources/sw_carpentry.md
            - Training:
                - "YCRC Workshops": https://research.computing.yale.edu/training
                - "YCRC YouTube Channel": https://ycrc.yale.edu/youtube

            - resources/national-hpcs.md
            - resources/glossary.md
